# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Product.create(name: "artichoke", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "aubergine", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Batavia green / red", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "cauliflower", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "floor kohlrabi", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "beans", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "broccoli", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Catalogna", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Chicory", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Chinese cabbage", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Cicorino Rosso", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Eichblatt green / red", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "iceberg lettuce", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Endive curled /  smooth", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "fennel", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "cucumber", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "turnip", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "carrot", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Carrot bunch", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "kefen", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "garlic", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "celery root", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "kohlrabi", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Lettuce green / red", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Krautstiel / Mangold", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "pumpkin", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "lettuce", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "leek", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Lollo green / red", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "melon", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Lamb's lettuce", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Pak choi", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "parsnip", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "pepperoni", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "parsley", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Pfälzerrübe", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "purslane", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "radish", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "the edge", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "radish", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Romanesco", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Brussels sprouts", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Rotkabis", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "arugula", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Salads from hydro production", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "shallot", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "chives", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Leaf lettuce", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "spinach", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "celery", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Tomato cherry", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Tomato date", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Tomato peretti", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Tomato panicle", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Tomato round", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "white cabbage", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Wirz", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Zucchetti", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Sugarloaf", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Sweet corn", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "onion", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Onion fret", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Peas (fresh)", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Spring cabbage / kale", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Kalettes ®", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Kardy", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "turnip", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "rhubarb", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "salsify", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Asparagus green / white", water_usage: 10, co2_usage: 100, people_usage: 100)
Product.create(name: "Jerusalem artichokes", water_usage: 10, co2_usage: 100, people_usage: 100)
